-- ==============================================================================
-- 006_study_notes.sql
-- Creates the persistent storage table for Miss Wena's 2-Way Study Notes
-- ==============================================================================

CREATE TABLE public.study_notes (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
    subject TEXT NOT NULL,           -- e.g., 'mathematics', 'science', 'english'
    topic TEXT,                      -- e.g., 'fractions', 'light', 'grammar'
    title TEXT NOT NULL,             -- AI generated, e.g., "Mastering the Before-After Concept"
    content_html TEXT NOT NULL,      -- The rich HTML 2-way note generated by Miss Wena
    is_read BOOLEAN DEFAULT FALSE,   -- Supports "New" badge in the Dashboard Backpack
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Index for fast retrieval when loading all of a student's notes (Option B - Backpack)
CREATE INDEX idx_study_notes_student_id ON public.study_notes(student_id);
-- Indices for contextual filtering on the Progress Page (Option A - Revision Vault)
CREATE INDEX idx_study_notes_subject ON public.study_notes(subject);
CREATE INDEX idx_study_notes_topic ON public.study_notes(topic);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ==============================================================================
ALTER TABLE public.study_notes ENABLE ROW LEVEL SECURITY;

-- 1. SELECT Policy: Parents can only read notes belonging to their own children
CREATE POLICY "Parents can view their children's study notes"
    ON public.study_notes FOR SELECT
    USING (
        student_id IN (
            SELECT id FROM public.students WHERE parent_id = auth.uid()
        )
    );

-- 2. DELETE Policy: Parents can delete notes to keep the vault clean
CREATE POLICY "Parents can delete their children's study notes"
    ON public.study_notes FOR DELETE
    USING (
        student_id IN (
            SELECT id FROM public.students WHERE parent_id = auth.uid()
        )
    );

-- 3. UPDATE Policy: Parents can update notes (needed to mark notes as read)
CREATE POLICY "Parents can update their children's study notes"
    ON public.study_notes FOR UPDATE
    USING (
        student_id IN (
            SELECT id FROM public.students WHERE parent_id = auth.uid()
        )
    );

-- NOTE: 
-- There is purposefully no INSERT policy here. 
-- To prevent malicious code injection from the frontend, all new notes MUST be 
-- inserted securely by the backend (`/api/summarize-chat`) using the admin `getAdminClient()`.